#pragma once

#include "NativeGameplayTags.h"

namespace AlsLocomotionModeTags
{
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flying)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swimming)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sliding)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FreeClimbing)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RopeSwing)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gliding)
}

namespace AlsLocomotionActionTags
{
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackCombo)
}