#pragma once

#include "NativeGameplayTags.h"

namespace AlsLocomotionModeTags
{
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flying)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swimming)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sliding)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FreeClimbing)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RopeSwing)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gliding)
}

namespace AlsLocomotionActionTags
{
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LocomotionActionParent)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackCombo)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ClimbDownLedge)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ClimbDownFloor)
}

namespace AlsSwimmingStateTags
{
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwimmingStateParent)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Surface)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Underwater)
}

namespace AlsDamageTypeTags
{
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fall)
	ALSEXTEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdoll)
}